### ISSUE TITLE
Synchronizing self-hosted

### ISSUE THREAD

**Issue by MyBlood** [financier-io/financier#6]
Greetings!

Will synchronization work if I put Financier on my server?

**Comment by aeharding** [comment]
It's definitely possible, but there will need to be a few code changes to setup the database.

Here's some examples:

- https://www.reddit.com/r/financier/comments/7d9osz/scripts_for_running_financier_fork_on_own_server/
- https://www.reddit.com/r/financier/comments/t59jec/could_someone_walk_me_through_setting_this_up_on/
- https://hub.docker.com/r/tbi88/financier
