### ISSUE TITLE
select balance

### ISSUE THREAD

**Issue by deanet** [financier-io/financier#8]
could you add the feature like "Selected Balance" ??

![image](https://user-images.githubusercontent.com/275259/200237930-036e0a16-55e1-4e00-94c2-9c82c408a4bf.png)

**Comment by aeharding** [comment]
I'm confused - there is a "selected balance" in the header of your screenshot. Is that what you're asking about?

**Comment by deanet** [comment]
yes, that is what i am asking about. i've run another fork of your repo with feature "selected balance", but it's not working properly.

could you please add it to the new feature ?

**Comment by deanet** [comment]
i've used HomeBank, it's more useful than this apps. 

IMHO also, HomeBank is more useful than YNAB. I think YNAB just got the idea from HomeBank, the features of YNAB are similar to HomeBank.
